openapi: 3.0.3
info:
  title: "Federated Manga Key Exchange API"
  version: "0.0.1"
servers:
- url: https://manga.example.com
tags:
- name: keys
  description: Exchanging signing keys between servers
paths:
  "/v1/keys/query/{serverName}":
    get:
      tags:
      - keys
      summary: Query for another server's keys
      description: |-
        Query for another server's keys. If requested by a witness, the witness must
        sign the keys returned by the queried server. Most likely, the witness will either
        be a well-known volunteer load balancer, or another mirror.
      operationId: perspectivesKeyQuery
      parameters:
        - in: path
          name: serverName
          schema:
            type: string
          description: The server's DNS name to query
          required: true
          x-example: matrix.org
        - in: query
          name: minimum_valid_until_ts
          schema:
            type: integer
            format: int64
          description: |-
            A POSIX timestamp in milliseconds indicating when the returned certificates
            will need to be valid until for it to be useful to the requesting server.

            If not supplied, the current time as determined by the witness is used.
          required: false
          x-example: 1234567890
      responses:
        200:
          description: |-
            The keys for the server, or an empty array if the server could not be reached
            and no cached keys were available.
          content:
            application/json:
              schema:
                $ref: "definitions/keys_query_response.yaml#/components/schemas/WitnessedServerKeys"
  "/v1/keys/query":
    post:
      tags:
      - keys
      summary: Query for several server's keys
      description: |-
        Query for keys from multiple servers in a batch format.  If requested by a witness,
        the witness must sign the keys returned by the queried servers.
      operationId: bulkPerspectivesKeyQuery
      requestBody:
        description: foobar
        required: true
        content:
          application/json:
            schema:
              type: object
              example: {
                "server_keys": {
                  "manga.example.org/v1": {
                    "ed25519:abc123": {
                      "minimum_valid_until_ts": 1234567890
                    }
                  }
                }
              }
              properties:
                server_keys:
                  type: object
                  description: |-
                    The query. The outer `string` key on the object is the
                    server name (eg: `manga.example.com/v1`). The inner `string` key is the
                    key ID to query for the particular server. If no key IDs are given
                    to be queried, the witness should query for all keys. If no
                    servers are given, the witness must return an empty `server_keys`
                    array in the response.
  
                    The witness may return multiple keys regardless of the Key IDs
                    given.
                  additionalProperties:
                    type: object
                    title: ServerName
                    description: The server names to query.
                    additionalProperties:
                      type: object
                      title: Query Criteria
                      description: The server key IDs to query.
                      properties:
                        minimum_valid_until_ts:
                          type: integer
                          format: int64
                          description: |-
                            A millisecond POSIX timestamp in milliseconds indicating when
                            the returned certificates will need to be valid until to be
                            useful to the requesting server.
  
                            If not supplied, the current time as determined by the witness is used.
                            example: 1234567890
              required:
              - server_keys
      responses:
        200:
          description: |-
            The keys for the queried servers, signed by the witness. Servers which
            are offline and have no cached keys will not be included in the result. This
            may result in an empty array.
          content:
            application/json:
              schema:
                $ref: "definitions/keys_query_response.yaml#/components/schemas/WitnessedServerKeys"